# Generated by Django 4.0 on 2021-12-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='slug',
            field=models.SlugField(default='defaultclient', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
